name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
            docker-compose down
            docker-compose rm -f
            docker-compose up -d --build
          EOF

      - name: Clean up SSH
        run: rm -rf ~/.ssh

        - name: Run tests
        run: npm test -- --passWithNoTests

        - name: Backup database
  run: |
    ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
      cd ${{ secrets.WORK_DIR }}
      docker exec <nom-conteneur-db> pg_dump -U user mydb > backup_$(date +%F).sql
    EOF  
    